FROM python:3.9-slim

# Install dependencies
RUN apt-get update && \
    apt-get install -y python3-distutils && \
    pip install --upgrade pip

# Set working directory
WORKDIR /data

# Copy project files
COPY . .

# Install Django
RUN pip install django==3.2

# Run migrations
RUN python manage.py migrate

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]



